version: '3.2'
  
services:
  fluentd:
    container_name: fluentd
    build:
      context: .
      dockerfile: build/fluentd/Dockerfile 
    image: fluentd
    restart: always
    volumes:
      # - ./data/fluentd/log:/fluentd/log
      # - ./data/fluentd/pos:/fluentd/pos
      # - /opt/dionaea/var/lib/dionaea:/fluentd/sources/dionaea
      # - /opt/cowrie-docker/data/log:/fluentd/sources/cowrie
    ports: 
      - 24224:24224
      #- 9880:9880
    volumes:
      - ./conf/fluentd:/fluentd/etc
    # environment:
    #   - FLUENTD_CONF=fluentd.cfg
    #  FLUENT_UID:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   container_name: mongo_express
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
